import type {
  BodyRegionDefinition,
  BodyRegionId,
  BodyRegionState,
  RegionalNodeDefinition,
  RegionalNodeId,
} from "./bodyMapTypes";

export const bodyRegionOrder: BodyRegionId[] = [
  "skin",
  "lungs",
  "intestine",
  "blood",
  "lymphNodes",
  "spleen",
  "boneMarrow",
  "liver",
];

export const bodyRegionDefinitions: Record<BodyRegionId, BodyRegionDefinition> = {
  skin: {
    id: "skin",
    name: "Peau",
    regionType: "barrier",
    mapPosition: { x: 18, y: 28 },
    connections: ["blood", "lymphNodes"],
    regionalNodeId: "skinNode",
    linkedMissionId: "skinBacterialSkirmish",
    tacticalMapId: "skin_multi_wound_template",
    preferredThreat: "bacterial",
    pedagogy:
      "La peau est une barriere. Une plaie peut laisser entrer des bacteries vers la lymphe puis le sang.",
    visualIdentity: {
      shapeHint: "surface protectrice avec fissure",
      colorHint: "rose corail et turquoise de soin",
      silhouetteHint: "plaque externe lisible",
      animationHint: "pulsation de plaie et cicatrisation lente",
      effectHint: "particules de debris cutanes",
      sizeClass: "large",
      movementStyle: "static_region",
      vfxTags: ["barrier", "wound", "bacteria"],
      futureSpriteKey: "region_skin",
      futureSoundHint: "soft_skin_pulse",
    },
  },
  lungs: {
    id: "lungs",
    name: "Poumons",
    regionType: "respiratory",
    mapPosition: { x: 48, y: 20 },
    connections: ["blood", "lymphNodes"],
    regionalNodeId: "thoracicNode",
    linkedMissionId: "lungViralSpread",
    tacticalMapId: "lung_branching_vessels_template",
    preferredThreat: "viral",
    pedagogy:
      "Les poumons exposent beaucoup de cellules aux virus respiratoires. Les interferons ralentissent la propagation.",
    visualIdentity: {
      shapeHint: "deux lobes respiratoires stylises",
      colorHint: "bleu clair et violet viral",
      silhouetteHint: "double poche aerienne",
      animationHint: "respiration lente avec nuages viraux",
      effectHint: "souffle d'interferons",
      sizeClass: "large",
      movementStyle: "breathing_region",
      vfxTags: ["lungs", "virus", "airflow"],
      futureSpriteKey: "region_lungs",
      futureSoundHint: "breath_soft",
    },
  },
  intestine: {
    id: "intestine",
    name: "Intestin",
    regionType: "digestive",
    mapPosition: { x: 52, y: 66 },
    connections: ["blood", "lymphNodes", "liver"],
    regionalNodeId: "gutNode",
    linkedMissionId: "intestineBacillusSwarm",
    tacticalMapId: "intestine_clustered_sites_template",
    preferredThreat: "bacterial",
    pedagogy:
      "L'intestin concentre beaucoup de microbes. Le gameplay le simplifie en foyer bacterien dense.",
    visualIdentity: {
      shapeHint: "courbe digestive segmente",
      colorHint: "orange biologique et vert microbien",
      silhouetteHint: "tube replie",
      animationHint: "peristaltisme discret",
      effectHint: "microbes en essaim",
      sizeClass: "large",
      movementStyle: "looping_region",
      vfxTags: ["gut", "bacteria", "dense"],
      futureSpriteKey: "region_intestine",
      futureSoundHint: "gut_low_pulse",
    },
  },
  blood: {
    id: "blood",
    name: "Sang",
    regionType: "circulation",
    mapPosition: { x: 34, y: 47 },
    connections: ["skin", "lungs", "intestine", "spleen", "boneMarrow", "liver"],
    regionalNodeId: "bloodNode",
    linkedMissionId: "bloodMixedAlert",
    tacticalMapId: "blood_vessel_crossroads_template",
    preferredThreat: "mixed",
    pedagogy:
      "Le sang transporte les cellules immunitaires, mais il peut aussi accelerer une propagation systemique.",
    visualIdentity: {
      shapeHint: "reseau de vaisseaux",
      colorHint: "rouge profond et cyan immunitaire",
      silhouetteHint: "carrefour circulatoire",
      animationHint: "flux continu",
      effectHint: "trainees de propagation",
      sizeClass: "systemic",
      movementStyle: "flow_region",
      vfxTags: ["blood", "systemic", "spread"],
      futureSpriteKey: "region_blood",
      futureSoundHint: "vascular_flow",
    },
  },
  lymphNodes: {
    id: "lymphNodes",
    name: "Ganglions lymphatiques",
    regionType: "lymphatic",
    mapPosition: { x: 68, y: 42 },
    connections: ["skin", "lungs", "intestine", "blood", "spleen"],
    regionalNodeId: "bloodNode",
    linkedMissionId: "lymphNodeSignalResponse",
    tacticalMapId: "lymph_node_signal_template",
    preferredThreat: "mixed",
    pedagogy:
      "La lymphe transporte les informations antigeniques vers les ganglions regionaux.",
    visualIdentity: {
      shapeHint: "chaine de ganglions connectes",
      colorHint: "violet clair et cyan signal",
      silhouetteHint: "grappes de noeuds",
      animationHint: "impulsions de signaux antigeniques",
      effectHint: "lignes lumineuses de lymphe",
      sizeClass: "medium",
      movementStyle: "signal_region",
      vfxTags: ["lymph", "antigen", "signal"],
      futureSpriteKey: "region_lymph_nodes",
      futureSoundHint: "signal_chime",
    },
  },
  spleen: {
    id: "spleen",
    name: "Rate",
    regionType: "immuneOrgan",
    mapPosition: { x: 78, y: 55 },
    connections: ["blood", "lymphNodes", "liver"],
    regionalNodeId: "bloodNode",
    linkedMissionId: "spleenBloodFiltering",
    tacticalMapId: "blood_vessel_crossroads_template",
    preferredThreat: "mixed",
    pedagogy:
      "La rate surveille le sang. Dans V7, elle sert surtout de relais strategique immunitaire.",
    visualIdentity: {
      shapeHint: "filtre organique arrondi",
      colorHint: "pourpre sombre et rouge filtre",
      silhouetteHint: "organe compact",
      animationHint: "filtrage par vagues",
      effectHint: "particules capturees",
      sizeClass: "medium",
      movementStyle: "filter_region",
      vfxTags: ["spleen", "filter", "blood"],
      futureSpriteKey: "region_spleen",
      futureSoundHint: "filter_pulse",
    },
  },
  boneMarrow: {
    id: "boneMarrow",
    name: "Moelle osseuse",
    regionType: "production",
    mapPosition: { x: 22, y: 76 },
    connections: ["blood"],
    regionalNodeId: "bloodNode",
    linkedMissionId: "boneMarrowReinforcementPressure",
    tacticalMapId: "blood_vessel_crossroads_template",
    preferredThreat: "none",
    pedagogy:
      "La moelle osseuse produit des cellules immunitaires. Si elle reste saine, les renforts restent accessibles.",
    visualIdentity: {
      shapeHint: "noyau de production cellulaire",
      colorHint: "jaune chaud et blanc cellulaire",
      silhouetteHint: "cavite lumineuse",
      animationHint: "apparition douce de nouvelles cellules",
      effectHint: "bulles de production",
      sizeClass: "medium",
      movementStyle: "production_region",
      vfxTags: ["marrow", "production", "reinforcement"],
      futureSpriteKey: "region_bone_marrow",
      futureSoundHint: "cell_spawn_soft",
    },
  },
  liver: {
    id: "liver",
    name: "Foie",
    regionType: "metabolic",
    mapPosition: { x: 72, y: 75 },
    connections: ["blood", "intestine", "spleen"],
    regionalNodeId: "bloodNode",
    linkedMissionId: "liverAbnormalGrowth",
    tacticalMapId: "blood_vessel_crossroads_template",
    preferredThreat: "cancer",
    pedagogy:
      "Le foie est une zone de stabilisation simplifiee. Une infection systemique le met sous pression.",
    visualIdentity: {
      shapeHint: "grand organe de stabilisation",
      colorHint: "ambre et violet d'alerte",
      silhouetteHint: "masse organique lisse",
      animationHint: "detoxification lente",
      effectHint: "halo metabolique",
      sizeClass: "large",
      movementStyle: "metabolic_region",
      vfxTags: ["liver", "metabolic", "abnormal"],
      futureSpriteKey: "region_liver",
      futureSoundHint: "low_metabolic_hum",
    },
  },
};

export const regionalNodeDefinitions: Record<
  RegionalNodeId,
  RegionalNodeDefinition
> = {
  skinNode: {
    id: "skinNode",
    name: "Ganglion peau",
    associatedRegionIds: ["skin"],
    description:
      "Recoit les signaux venus des tissus cutanes et accelere legerement l'analyse locale.",
  },
  thoracicNode: {
    id: "thoracicNode",
    name: "Ganglion thoracique",
    associatedRegionIds: ["lungs"],
    description:
      "Coordonne les signaux respiratoires et aide les reponses antivirales locales.",
  },
  gutNode: {
    id: "gutNode",
    name: "Ganglion intestinal",
    associatedRegionIds: ["intestine"],
    description:
      "Filtre les signaux digestifs et prepare une reponse adaptee aux foyers bacteriens.",
  },
  bloodNode: {
    id: "bloodNode",
    name: "Rate / relais systemique",
    associatedRegionIds: ["blood", "lymphNodes", "spleen", "boneMarrow", "liver"],
    description:
      "Relais strategique global pour les menaces circulantes et les signaux antigeniques.",
  },
};

export const initialBodyRegions: Record<BodyRegionId, BodyRegionState> = {
  skin: {
    id: "skin",
    status: "infected",
    localHealth: 78,
    infection: 58,
    inflammation: 34,
    threat: "bacterial",
    pathogens: ["cocciRapid", "proliferatingBacillus"],
    assignedReinforcements: { macrophage: 1 },
  },
  lungs: {
    id: "lungs",
    status: "alert",
    localHealth: 84,
    infection: 32,
    inflammation: 22,
    threat: "viral",
    pathogens: ["respiratoryVirus"],
    assignedReinforcements: {},
  },
  intestine: {
    id: "intestine",
    status: "alert",
    localHealth: 86,
    infection: 28,
    inflammation: 26,
    threat: "bacterial",
    pathogens: ["proliferatingBacillus", "resistantBacterium"],
    assignedReinforcements: {},
  },
  blood: {
    id: "blood",
    status: "healthy",
    localHealth: 92,
    infection: 12,
    inflammation: 14,
    threat: "none",
    pathogens: [],
    assignedReinforcements: {},
  },
  lymphNodes: {
    id: "lymphNodes",
    status: "controlled",
    localHealth: 90,
    infection: 8,
    inflammation: 18,
    threat: "none",
    pathogens: [],
    assignedReinforcements: {},
  },
  spleen: {
    id: "spleen",
    status: "healthy",
    localHealth: 94,
    infection: 5,
    inflammation: 12,
    threat: "none",
    pathogens: [],
    assignedReinforcements: {},
  },
  boneMarrow: {
    id: "boneMarrow",
    status: "healthy",
    localHealth: 96,
    infection: 2,
    inflammation: 8,
    threat: "none",
    pathogens: [],
    assignedReinforcements: {},
  },
  liver: {
    id: "liver",
    status: "healthy",
    localHealth: 92,
    infection: 6,
    inflammation: 12,
    threat: "none",
    pathogens: [],
    assignedReinforcements: {},
  },
};
